version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql 
      - DB_PORT=3306
      - DB_DATABASE=homebase
      - DB_USERNAME=user
      - DB_PASSWORD=userpassword
      

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

networks:
    laravel_network:
        driver: bridge 
